FROM golang:1.10.2-alpine3.7

LABEL maintainer="LIUYE, BUAA <liuye5@live.com>"

RUN mkdir -p /ContractFuzzer 

WORKDIR /ContractFuzzer

ADD go-ethereum-cf go-ethereum
ADD Ethereum Ethereum

ADD geth_run.sh  geth_run.sh
RUN apk add --update git go make gcc musl-dev linux-headers \
  && (cd go-ethereum && make geth) \
  && cp go-ethereum/build/bin/geth /usr/local/bin/ \
  && apk del git  make gcc musl-dev linux-headers \
  && rm -rf ./go-ethereum \
  && rm -rf /var/cache/apk/*

EXPOSE 8545
EXPOSE 30303
EXPOSE 30303/udp

CMD ["/bin/sh","geth_run.sh"]

